"""projects table include many to one author reference for poms

Revision ID: 1c1450481271
Revises: 82e72d0dbac7
Create Date: 2018-08-21 22:11:02.635386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c1450481271'
down_revision = '82e72d0dbac7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pomodoro_body', table_name='pomodoro')
    op.drop_index('ix_pomodoro_timestamp_end', table_name='pomodoro')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_pomodoro_timestamp_end', 'pomodoro', ['timestamp_end'], unique=False)
    op.create_index('ix_pomodoro_body', 'pomodoro', ['body'], unique=1)
    # ### end Alembic commands ###
