"""projects table change

Revision ID: 28d2debed3f1
Revises: 5c96bd3cf69e
Create Date: 2018-08-20 23:08:51.746604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28d2debed3f1'
down_revision = '5c96bd3cf69e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('cycle_num', sa.Integer(), nullable=True))
    op.add_column('project', sa.Column('l_break_length', sa.Integer(), nullable=True))
    op.add_column('project', sa.Column('pom_num', sa.Integer(), nullable=True))
    op.add_column('project', sa.Column('s_break_length', sa.Integer(), nullable=True))
    op.add_column('project', sa.Column('study_length', sa.Integer(), nullable=True))
    op.add_column('project', sa.Column('summary_length', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'summary_length')
    op.drop_column('project', 'study_length')
    op.drop_column('project', 's_break_length')
    op.drop_column('project', 'pom_num')
    op.drop_column('project', 'l_break_length')
    op.drop_column('project', 'cycle_num')
    # ### end Alembic commands ###
