"""empty message

Revision ID: 642b731ae779
Revises: 155a4699197e
Create Date: 2018-10-21 20:24:08.360383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '642b731ae779'
down_revision = '155a4699197e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('last_timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_project_last_timestamp'), 'project', ['last_timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_last_timestamp'), table_name='project')
    op.drop_column('project', 'last_timestamp')
    # ### end Alembic commands ###
