"""project upgrad: titles are not unique

Revision ID: 6f41b7a54003
Revises: 1c1450481271
Create Date: 2018-08-23 23:02:44.330385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f41b7a54003'
down_revision = '1c1450481271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_pomodoro_timestamp_end'), 'pomodoro', ['timestamp_end'], unique=False)
    op.drop_index('ix_project_title', table_name='project')
    op.create_index(op.f('ix_project_title'), 'project', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_title'), table_name='project')
    op.create_index('ix_project_title', 'project', ['title'], unique=1)
    op.drop_index(op.f('ix_pomodoro_timestamp_end'), table_name='pomodoro')
    # ### end Alembic commands ###
