"""pomodoros table upgrade

Revision ID: 82e72d0dbac7
Revises: 28d2debed3f1
Create Date: 2018-08-21 21:47:59.143458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82e72d0dbac7'
down_revision = '28d2debed3f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pomodoro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session', sa.Integer(), nullable=True),
    sa.Column('body', sa.String(length=420), nullable=True),
    sa.Column('is_aim', sa.Boolean(), nullable=True),
    sa.Column('timestamp_start', sa.DateTime(), nullable=True),
    sa.Column('timestamp_end', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pomodoro_body'), 'pomodoro', ['body'], unique=True)
    op.create_index(op.f('ix_pomodoro_timestamp_end'), 'pomodoro', ['timestamp_end'], unique=False)
    op.create_index(op.f('ix_pomodoro_timestamp_start'), 'pomodoro', ['timestamp_start'], unique=False)
    op.add_column(u'project', sa.Column('num_sessions', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'project', 'num_sessions')
    op.drop_index(op.f('ix_pomodoro_timestamp_start'), table_name='pomodoro')
    op.drop_index(op.f('ix_pomodoro_timestamp_end'), table_name='pomodoro')
    op.drop_index(op.f('ix_pomodoro_body'), table_name='pomodoro')
    op.drop_table('pomodoro')
    # ### end Alembic commands ###
